-- إنشاء جدول تاريخ أسعار الفئات الفرعية
CREATE TABLE IF NOT EXISTS public.subcategory_price_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subcategory_id BIGINT NOT NULL REFERENCES public.waste_sub_categories(id),
    old_buy_price NUMERIC,
    new_buy_price NUMERIC NOT NULL,
    old_sell_price NUMERIC,
    new_sell_price NUMERIC,
    changed_by UUID REFERENCES auth.users(id),
    change_reason TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- تفعيل RLS
ALTER TABLE public.subcategory_price_history ENABLE ROW LEVEL SECURITY;

-- سياسات الأمان
CREATE POLICY "Admins can view and insert subcategory history" ON public.subcategory_price_history
    FOR ALL USING (
        EXISTS (SELECT 1 FROM public.admins WHERE id = auth.uid()) OR 
        EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin')
    );
